#! /usr/bin/with-contenv bash

#设置umask

UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"

# 启动qBittorrent

if [ "$QB_EE_BIN" == "true" ]; then

exec s6-setuidgid abc qbittorrent-nox --webui-port=$WEBUIPORT --profile=/config 
