#!/usr/bin/with-contenv bash

# 检查config配置文件，并创建
if [ ! -e "/config/qBittorrent/config/qBittorrent.conf" ] ;  then 
mkdir -p /config/qBittorrent/config/
cp /usr/local/qbittorrent/defaults/qBittorrent.conf  /config/qBittorrent/config/qBittorrent.conf
fi

# 检查Search文件，并创建.
if [ ! -d "/config/qBittorrent/data/nova3/engines" ] ;  then 
mkdir -p /config/qBittorrent/data/nova3/engines
fi
cp -ru /usr/local/qbittorrent/defaults/Search/*  /config/qBittorrent/data/nova3/engines

# 检查qb_auto.sh文件，并创建.
if [ ! -e "/upload/qb_auto.sh" ] ;  then 
mkdir -p /upload
cp /usr/local/qbittorrent/qb_auto.sh  /upload/qb_auto.sh
fi

# permissions
chown -R abc:abc \
	/config \
    /downloads
    /upload

